### PR TITLE
🔀 Remove unnecessary dependencies and code refactor

### PR DESCRIPTION
**Pull request by guedesfelipe**
[fc2037e](https://github.com/NayamAmarshe/please/pull/14/commits/fc2037ea6161c841b084a7e6c25a5b4d6b02892a): Remove unnecessary dependencies and change autopep8 to dev dependency.

[8dee6e1](https://github.com/NayamAmarshe/please/pull/14/commits/8dee6e18c3b1d8f5d335e2a1359973fb6028f5bd): Use f-string an in my terminal, Italics render like this:

And that's because in the empty space there are italic characters `\e[3`

After refactor:

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
Thanks for the PR and very sorry for the late response. I'll take a look at the code changes and review as soon as possible.

**Review by NayamAmarshe — APPROVED** [review]
Merging, thanks for the changes.

**Comment by NayamAmarshe** [comment]
@guedesfelipe Could you please resolve the merge issues?

**Comment by guedesfelipe** [comment]
> @guedesfelipe Could you please resolve the merge issues?

Sure, as soon as possible I'll take a look

**Comment by guedesfelipe** [comment]
@NayamAmarshe Done!

**Pull request merged**
